spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/efubtoy?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: '0420'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties: # 이 부분을 추가해야 합니다.
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8을 사용하는 경우
        # dialect: org.hibernate.dialect.MySQLDialect # 이전 MySQL 버전이거나 정확히 모르면 이것도 시도해볼 수 있습니다.