spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://efub-b.cpyw0aga6sbd.ap-northeast-2.rds.amazonaws.com:3306/efubb?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: wjddbwjd72
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true